"""Generate scratchpad/reach/cases.py: one obligation per source LINE.

Identity of an obligation is its call-site line: stelling's
`source_info[-1]` is the user frame (`file:line (fn)`), and the oracle
reads the same line from `inspect.currentframe().f_back.f_lineno`.
Every `S(...)` call is therefore emitted on its own single line.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "cases.py")

# guard-key -> (expression, ground-truth class)
#   dt = definitely-true over the declared box
#   df = definitely-false over the declared box
#   sat = both polarities occur in the declared box
GUARDS = {
    "lit_true":   ("True", "dt"),
    "lit_false":  ("False", "df"),
    "iv_true":    ("c > 0.0", "dt"),          # c in (1,2)
    "iv_false":   ("c > 5.0", "df"),
    "sat":        ("x[0] > 0.0", "sat"),      # x in (-1,1)
    "hidden_f":   ("x[0] - x[0] > 0.0", "df"),
    "hidden_t":   ("x[0] - x[0] <= 0.0", "dt"),
    "top_sat":    ("jnp.sin(x[0]) > 0.0", "sat"),
    "top_hid_f":  ("jnp.sin(x[0] * 0.0) > 0.0", "df"),
    # satisfiable through REGISTERED primitives only: interval still
    # straddles ([0,1] vs 0.25) but a point probe can evaluate it. This
    # separates "the guard is satisfiable" from "the guard runs through a
    # primitive stelling cannot evaluate at all" -- without it the two
    # would be one bucket and the cost ledger could not tell them apart.
    "reg_sat":    ("x[0] * x[0] > 0.25", "sat"),
    # satisfiable only on a NARROW window: the deliberate probe-precision
    # control. A finite witness grid is a sufficient, never a necessary,
    # reachability certificate and this measures the gap.
    "narrow_sat": ("(x[0] > 0.62) & (x[0] < 0.63)", "sat"),
}

# predicate-key -> (expression over `v` (shape (3,), in (-1,1)), truth class)
VPRED = {
    "true":  ("v > -9.0", "T"),
    "false": ("v > 5.0", "F"),
    "mixed": ("v > 0.0", "M"),
}
# top-level predicate over `c` in (1,2)
CPRED = {
    "true":  ("c > 0.0", "T"),
    "false": ("c > 5.0", "F"),
    "mixed": ("c > 1.5", "M"),
}

lines = []
meta = []  # (case_name, dict of knobs)
w = lines.append

w('"""GENERATED by gen_cases.py -- do not edit. One S() call per line."""')
w("import jax")
w("import jax.numpy as jnp")
w("")


def emit_cond_case(name, gk, yk, nk, tk):
    guard, _ = GUARDS[gk]
    w(f"def {name}(A, S, C):")
    w('    x = A("x", (3,), "float64", (-1.0, 1.0))')
    w('    c = A("c", (), "float64", (1.0, 2.0))')
    w("    outs = []")
    if tk is not None:
        w(f"    outs.append(S({CPRED[tk][0]}))")
    # FILLER (no obligation) is a plain comparison, never an assert: the
    # blind spot the last corpus hit was an unfalsifiable filler CLAIM in
    # the sibling branch. A non-assert filler states nothing, and the
    # sibling's real obligation is varied over {none, true, false, mixed}
    # so the sibling slot discriminates.
    ybody = f"S({VPRED[yk][0]})" if yk else "v > 3.0"
    nbody = f"S({VPRED[nk][0]})" if nk else "v < 3.0"
    w(f"    yb = lambda v: {ybody}")
    w(f"    nb = lambda v: {nbody}")
    w(f"    outs.append(C.cond({guard}, yb, nb, x))")
    w("    return tuple(outs)")
    w("")


n = 0
for gk in GUARDS:
    for yk in (None, "true", "false", "mixed"):
        for nk in (None, "true", "false", "mixed"):
            for tk in (None, "true", "false", "mixed"):
                nm = f"c_{gk}__y_{yk}__n_{nk}__t_{tk}"
                emit_cond_case(nm, gk, yk, nk, tk)
                meta.append((nm, dict(family="cond", guard=gk,
                                      guard_truth=GUARDS[gk][1],
                                      yes=yk, no=nk, top=tk)))
                n += 1

# ---- switch family: 3 branches, index from a declared int ------------------
for gk, gexpr, gtruth in [
    ("sw_sat", "jnp.int32(jnp.floor(c))", "sat"),      # c in (1,2) -> {1,2}
    ("sw_df1", "jnp.int32(jnp.floor(c)) * 0", "df"),   # always 0
    ("sw_hid", "jnp.int32(jnp.floor(c - c))", "df"),   # always 0, interval-blind
]:
    for placement in ("b0", "b1", "b2", "all"):
        nm = f"s_{gk}__{placement}"
        w(f"def {nm}(A, S, C):")
        w('    x = A("x", (3,), "float64", (-1.0, 1.0))')
        w('    c = A("c", (), "float64", (1.0, 2.0))')
        w("    outs = []")
        w("    outs.append(S(c > 0.0))")
        for b in range(3):
            hit = placement == "all" or placement == f"b{b}"
            body = "S(v > 5.0)" if hit else f"v > {b + 1}.0"
            w(f"    b{b} = lambda v: {body}")
        w(f"    outs.append(C.switch({gexpr}, [b0, b1, b2], x))")
        w("    return tuple(outs)")
        w("")
        meta.append((nm, dict(family="switch", guard=gk, guard_truth=gtruth,
                              yes=placement, no=None, top="true")))

# ---- scan family ----------------------------------------------------------
for nm, pred, cls in [
    ("k_scan_false", "v > 5.0", "F"),
    ("k_scan_true", "v > -9.0", "T"),
    ("k_scan_mixed", "v > 1.5", "M"),
]:
    for tk in ("true", "false", None):
        full = f"{nm}__t_{tk}"
        w(f"def {full}(A, S, C):")
        w('    x = A("x", (3,), "float64", (1.0, 2.0))')
        w('    c = A("c", (), "float64", (1.0, 2.0))')
        w("    outs = []")
        if tk is not None:
            w(f"    outs.append(S({CPRED[tk][0]}))")
        w(f"    body = lambda a, v: (a, S({pred}))")
        w("    outs.append(C.scan(body, 0.0, x))")
        w("    return tuple(outs)")
        w("")
        meta.append((full, dict(family="scan", guard="none", guard_truth="dt",
                                yes=cls, no=None, top=tk)))

# ---- while family ---------------------------------------------------------
for nm, pred, cls in [
    ("k_while_false", "a > 5.0", "F"),
    ("k_while_true", "a > -9.0", "T"),
]:
    for tk in ("true", None):
        full = f"{nm}__t_{tk}"
        w(f"def {full}(A, S, C):")
        w('    x = A("x", (3,), "float64", (1.0, 2.0))')
        w('    c = A("c", (), "float64", (1.0, 2.0))')
        w("    outs = []")
        if tk is not None:
            w(f"    outs.append(S({CPRED[tk][0]}))")
        w("    def bf(s):")
        w("        i, a = s")
        w(f"        return (i + 1, jnp.where(S({pred}), a, a))")
        w("    outs.append(C.while_loop(lambda s: s[0] < 3, bf, (0, x[0])))")
        w("    return tuple(outs)")
        w("")
        meta.append((full, dict(family="while", guard="none", guard_truth="dt",
                                yes=cls, no=None, top=tk)))

# ---- nested families ------------------------------------------------------
# cond inside cond: outer guard hidden-false, inner obligation false
NEST = [
    ("n_cc_hidfalse_out", "x[0] - x[0] > 0.0", "x[0] > 0.0", "df", "sat"),
    ("n_cc_sat_out_hidfalse_in", "x[0] > 0.0", "x[1] - x[1] > 0.0", "sat", "df"),
    ("n_cc_sat_sat", "x[0] > 0.0", "x[1] > 0.0", "sat", "sat"),
    ("n_cc_dt_hidfalse_in", "c > 0.0", "x[1] - x[1] > 0.0", "dt", "df"),
]
for nm, og, ig, ot, it in NEST:
    w(f"def {nm}(A, S, C):")
    w('    x = A("x", (3,), "float64", (-1.0, 1.0))')
    w('    c = A("c", (), "float64", (1.0, 2.0))')
    w("    outs = []")
    w("    outs.append(S(c > 0.0))")
    w(f"    inner_y = lambda v: S(v > 5.0)")
    w(f"    inner_n = lambda v: S(v > -9.0)")
    w(f"    outer_y = lambda v: C.cond({ig}, inner_y, inner_n, v)")
    w(f"    outer_n = lambda v: S(v > -8.0)")
    w(f"    outs.append(C.cond({og}, outer_y, outer_n, x))")
    w("    return tuple(outs)")
    w("")
    meta.append((nm, dict(family="cond-in-cond", guard=nm, guard_truth=ot,
                          yes=it, no=None, top="true")))

# scan inside cond (unreachable branch swallows a scan obligation), and
# cond inside scan
w("def n_scan_in_cond_hidfalse(A, S, C):")
w('    x = A("x", (3,), "float64", (1.0, 2.0))')
w('    c = A("c", (), "float64", (1.0, 2.0))')
w("    outs = []")
w("    outs.append(S(c > 0.0))")
w("    yb = lambda v: C.scan(lambda a, e: (a, S(e > 5.0)), 0.0, v)[0]")
w("    nb = lambda v: v[0] * 1.0")
w("    outs.append(C.cond(x[0] - x[0] > 0.0, yb, nb, x))")
w("    return tuple(outs)")
w("")
meta.append(("n_scan_in_cond_hidfalse", dict(family="scan-in-cond",
                                             guard="hidden_f", guard_truth="df",
                                             yes="F", no=None, top="true")))

w("def n_cond_in_scan(A, S, C):")
w('    x = A("x", (3,), "float64", (1.0, 2.0))')
w('    c = A("c", (), "float64", (1.0, 2.0))')
w("    outs = []")
w("    outs.append(S(c > 0.0))")
w("    def body(a, e):")
w("        r = C.cond(e - e > 0.0, lambda u: S(u > 5.0), lambda u: S(u > -9.0), e)")
w("        return a, r")
w("    outs.append(C.scan(body, 0.0, x))")
w("    return tuple(outs)")
w("")
meta.append(("n_cond_in_scan", dict(family="cond-in-scan", guard="hidden_f",
                                    guard_truth="df", yes="F", no="T",
                                    top="true")))

# a jit wrapper (transparent) holding an obligation -- the control that
# must NOT move: jit IS descended today.
w("def j_jit_top(A, S, C):")
w('    x = A("x", (3,), "float64", (1.0, 2.0))')
w('    c = A("c", (), "float64", (1.0, 2.0))')
w("    outs = []")
w("    outs.append(S(c > 0.0))")
w("    outs.append(jax.jit(lambda v: S(v > 5.0))(x))")
w("    return tuple(outs)")
w("")
meta.append(("j_jit_top", dict(family="jit", guard="none", guard_truth="dt",
                               yes="F", no=None, top="true")))

w("CASES = {")
for nm, m in meta:
    w(f"    {nm!r}: ({nm}, {m!r}),")
w("}")
w("")

with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}: {len(meta)} cases, {len(lines)} lines")
