# SPDX-FileCopyrightText: 2026 Nicholas Ehsan Roy
# SPDX-License-Identifier: Apache-2.0

"""The supported-primitives page cannot drift from the live registries.

``docs/supported-primitives.md`` is GENERATED by
``docs/gen_supported_primitives.py`` from the live registries
(``TRANSFERS``/``IEEE_TRANSFERS`` and the transfer-side integer census in
:mod:`stelling.propagate`, the emission set, emission-side census, and
replay surface in :mod:`stelling.obligation`, the transparent set in
:mod:`stelling.coverage`). This test regenerates the page in memory and
compares byte-for-byte with the committed copy, so EITHER kind of drift
fails red: a hand edit to the page, or a registry change without a
regeneration. The generator itself fails if a quoted reason no longer
exists verbatim in the code, so stale citations fail here too.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_GEN = _ROOT / "docs" / "gen_supported_primitives.py"
_PAGE = _ROOT / "docs" / "supported-primitives.md"


def _generator():
    spec = importlib.util.spec_from_file_location(
        "gen_supported_primitives", _GEN
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_committed_page_matches_live_registries():
    assert _PAGE.exists(), (
        f"{_PAGE} is missing; generate it with: python {_GEN}"
    )
    expected = _generator().generate()
    committed = _PAGE.read_text(encoding="utf-8")
    assert committed == expected, (
        "docs/supported-primitives.md differs from what the live registries "
        "generate — either the page was edited by hand or a registry changed "
        "without regeneration. Regenerate with: "
        "python docs/gen_supported_primitives.py"
    )
